FROM python:3.12-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN pip install --no-cache-dir boto3 psycopg2-binary

# Copia el script (ya no necesitas copiar data/, pues se descarga de S3)
COPY IngestaPostgres.py ./

CMD ["python3", "IngestaPostgres.py"]
