FROM python:3.12-slim

WORKDIR /app
ENV PYTHONUNBUFFERED=1

RUN pip install --no-cache-dir boto3

# Copia el script con el nombre correcto
COPY upload_to_s3.py ./

# Copia la carpeta de datos
COPY data/ ./data/

CMD ["python3", "IngestaPostgres.py"]
